/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.invoice.main;

import com.invoice.control.Controller;
import com.invoice.display.Invoice;
import com.invoice.display.displaytable;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JTable;

/**
 *
 * @author marwa
 */
public class invoiceframe extends javax.swing.JFrame {

  
    public invoiceframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        invoicetable = new javax.swing.JTable();
        invoicetable.getSelectionModel().addListSelectionListener(controller);
        createinvoicebutton = new javax.swing.JButton();
        createinvoicebutton.addActionListener(controller);
        deleteinvoicebutton = new javax.swing.JButton();
        deleteinvoicebutton.addActionListener(controller);
        JLabel1 = new javax.swing.JLabel();
        JLabel2 = new javax.swing.JLabel();
        JLabel3 = new javax.swing.JLabel();
        invoicetotallabel = new javax.swing.JLabel();
        invoicenumberlabel = new javax.swing.JLabel();
        invoicedatelabel = new javax.swing.JLabel();
        customernamelabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table2 = new javax.swing.JTable();
        savebutton = new javax.swing.JButton();
        savebutton.addActionListener(controller);
        cancelbutton = new javax.swing.JButton();
        cancelbutton.addActionListener(controller);
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        loadfilemenuitem = new javax.swing.JMenuItem();
        loadfilemenuitem.addActionListener(controller);
        savefilemenuitem = new javax.swing.JMenuItem();
        savefilemenuitem.addActionListener(controller);

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        invoicetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(invoicetable);

        createinvoicebutton.setText("Create New Invoice");
        createinvoicebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createinvoicebuttonActionPerformed(evt);
            }
        });

        deleteinvoicebutton.setText("Delete Invoice");
        deleteinvoicebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteinvoicebuttonActionPerformed(evt);
            }
        });

        JLabel1.setText("Invoice Number");

        JLabel2.setText("Invoice Date");

        JLabel3.setText("Customer Name");

        invoicetotallabel.setText("Invoice Total");

        Table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(Table2);

        savebutton.setText("Save");

        cancelbutton.setText("Cancel");

        jMenu1.setText("File");

        loadfilemenuitem.setText("Load File");
        loadfilemenuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadfilemenuitemActionPerformed(evt);
            }
        });
        jMenu1.add(loadfilemenuitem);

        savefilemenuitem.setText("Save File");
        jMenu1.add(savefilemenuitem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(createinvoicebutton)
                .addGap(28, 28, 28)
                .addComponent(deleteinvoicebutton)
                .addGap(85, 85, 85)
                .addComponent(savebutton)
                .addGap(67, 67, 67)
                .addComponent(cancelbutton)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JLabel2)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(JLabel1)
                                    .addGap(65, 65, 65)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(invoicetotallabel)
                                    .addComponent(JLabel3))
                                .addGap(65, 65, 65)))
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(customernamelabel)
                            .addComponent(invoicedatelabel)
                            .addComponent(invoicenumberlabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(invoicenumberlabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLabel2)
                            .addComponent(invoicedatelabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLabel3)
                            .addComponent(customernamelabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(invoicetotallabel)
                            .addComponent(jLabel8))
                        .addGap(85, 85, 85)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteinvoicebutton)
                    .addComponent(createinvoicebutton)
                    .addComponent(savebutton)
                    .addComponent(cancelbutton))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteinvoicebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteinvoicebuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteinvoicebuttonActionPerformed

    private void loadfilemenuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadfilemenuitemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loadfilemenuitemActionPerformed

    private void createinvoicebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createinvoicebuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createinvoicebuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(invoiceframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(invoiceframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(invoiceframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(invoiceframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new invoiceframe().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel1;
    private javax.swing.JLabel JLabel2;
    private javax.swing.JLabel JLabel3;
    private javax.swing.JTable Table2;
    private javax.swing.JButton cancelbutton;
    private javax.swing.JButton createinvoicebutton;
    private javax.swing.JLabel customernamelabel;
    private javax.swing.JButton deleteinvoicebutton;
    private javax.swing.JLabel invoicedatelabel;
    private javax.swing.JLabel invoicenumberlabel;
    private javax.swing.JTable invoicetable;
    private javax.swing.JLabel invoicetotallabel;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem loadfilemenuitem;
    private javax.swing.JButton savebutton;
    private javax.swing.JMenuItem savefilemenuitem;
    // End of variables declaration//GEN-END:variables

    private ArrayList<Invoice> invoices;
    private Controller controller = new Controller(this);
 private displaytable dst;
 
    public ArrayList<Invoice> getInvoices() {
        return invoices;
    }
    public void setInvoices(ArrayList<Invoice> invoices) {
        this.invoices = invoices;
    }

    public displaytable getDst() {
        return dst;
    }

    public void setDst(displaytable dst) {
        this.dst = dst;
    }

    public JTable getTable2() {
        return Table2;
    }

    public JLabel getCustomernamelabel() {
        return customernamelabel;
    }

    public JLabel getInvoicedatelabel() {
        return invoicedatelabel;
    }

    public JTable getInvoicetable() {
        return invoicetable;
    }

    public JLabel getInvoicetotallabel() {
        return invoicetotallabel;
    }

    public Controller getController() {
        return controller;
    }

    public void setdisplaytable(displaytable dst) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    public void getdisplaytable() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    public Object getdisplaytablee() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

}
